[package]
name = "acir_composer"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
barretenberg = { path = "../barretenberg" }
base64 = "0.21.4"
flate2 = "1.0.27"
hex = "0.4.3"
thiserror = "1.0.49"
