[package]
name = "acir_composer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
barretenberg.workspace = true

base64 = "0.21.4"
flate2 = "1.0.27"
hex = "0.4.3"
thiserror = "1.0.49"
