name: Rust build&test fedora

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [arc-runner-set]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name:
      run: sudo apt update && sudo apt install -y git build-essential curl pkg-config
    - uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: cargo build -vv
    - name: Run tests
      run: cargo test -vv
